#!/bin/bash

rm ~/rpmbuild/RPMS/x86_64/libmlx4-*

tar zcvf libmlx4-1.0.4.tar.gz libmlx4-1.0.4/*
mv libmlx4-1.0.4.tar.gz ~/rpmbuild/SOURCES/
cd ~/rpmbuild/SPECS/ 

rpmbuild -bb libmlx4.spec 

service openibd stop

rpm -Uvh --force ~/rpmbuild/RPMS/x86_64/libmlx4-*.rpm

service opensmd start
