#!/bin/bash

rm ~/rpmbuild/RPMS/x86_64/librdmacm-*

tar zcvf librdmacm-1.0.16.tar.gz librdmacm-1.0.16/*
cp librdmacm-1.0.16/librdmacm.spec ~/rpmbuild/SPECS/
mv librdmacm-1.0.16.tar.gz ~/rpmbuild/SOURCES/
cd ~/rpmbuild/SPECS/

rpmbuild -bb librdmacm.spec

rpm -Uvh --force ~/rpmbuild/RPMS/x86_64/librdmacm-*.rpm
